In [480]:
import numpy as np

In [490]:
def householder_compute(x):
    alpha = x[0, 0] * (1 + np.linalg.norm(x) / abs(x[0, 0]))
    x = x / alpha
    x[0, 0] = 1
    return (x, 2/np.linalg.norm(x)**2)

In [757]:
def householder(x, b, w):
    if b != 0:
        a = float(b * np.matmul(x.T, w))
        x = x - a*w
    return x

In [758]:
X = np.matrix([[1,4,2], [2,9, 1], [7,4,3]])

In [759]:
Q = np.matrix([])
for i in range(X.shape[0]):
    x = X[i].T
    w, beta = householder_compute(x)
    K = (beta * np.matmul(w, w.T))
    Q = np.identity(K.shape[0]) - K
    X = Q.T * X
    if Q.shape == (1, 0):
        Q = np.identity(K.shape[0]) - K
    else:
        Q = np.matmul(Q, np.identity(K.shape[0]) - K)
    

In [760]:
Q

matrix([[1.00000000e+00, 1.73472348e-16, 1.11022302e-16],
        [1.73472348e-16, 1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 0.00000000e+00, 1.00000000e+00]])

In [761]:
W = []
B = []

In [851]:
X = np.matrix([[1,4,2], [2,9, 1], [7,4,3]])
def R(X):
    if X.size == 0:
        return X
    w, beta = householder_compute(X[0].T)
    X = (np.column_stack([householder(x.T, beta, w) for x in X]))
    X[1:, 1:] = R(X[1:, 1:])
    return X
R = R(X)


In [858]:
R[abs(R) < 1E-8] = 0
R

matrix([[-4.58257569, -8.72871561, -6.32831882],
        [ 0.        , -5.7030758 , -1.07277193],
        [ 0.        ,  0.        ,  3.17584502]])

In [857]:

np.linalg.qr(X.T)

(matrix([[-0.21821789, -0.03040792, -0.97542622],
         [-0.87287156, -0.44091486,  0.2090199 ],
         [-0.43643578,  0.89703369,  0.0696733 ]]),
 matrix([[-4.58257569, -8.72871561, -6.32831882],
         [ 0.        , -3.13201593,  0.71458616],
         [ 0.        ,  0.        , -5.78288402]]))