In [3]:
import numpy as np

In [24]:
def householder_compute(x):
    alpha = x[0, 0] * (1 + np.linalg.norm(x) / abs(x[0, 0]))
    x = x / alpha
    x[0, 0] = 1
    return (x, 2/np.linalg.norm(x)**2)

In [288]:
def householder(x, b, w):
    if b != 0:
        a = float(b * np.matmul(x.T, w))
        x = x - a*w
    print(np.asarray(x).shape)
    return np.asarray(x)

In [275]:
X = np.matrix([[1,4,2], [2,9, 1], [7,4,3]])

In [276]:
Q = np.matrix([])
for i in range(X.shape[0]):
    x = X[i].T
    w, beta = householder_compute(x)
    K = (beta * np.matmul(w, w.T))
    Q = np.identity(K.shape[0]) - K
    X = Q.T * X
    if Q.shape == (1, 0):
        Q = np.identity(K.shape[0]) - K
    else:
        Q = np.matmul(Q, np.identity(K.shape[0]) - K)
    

In [277]:
Q

matrix([[1.00000000e+00, 1.73472348e-16, 1.11022302e-16],
        [1.73472348e-16, 1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 0.00000000e+00, 1.00000000e+00]])

In [278]:
W = []
B = []

In [298]:
X = np.matrix([[1,4,2], [2,9, 1], [7,4,3]])
def R(X):
    if X.size == 1:
        return X
    w, beta = householder_compute(X[0:, 0])
    #print([np.asarray(X[0:, i]) for i in range(X.shape[1])])
    X = np.column_stack([householder(np.asarray(X[0:, i]), beta, w)  for i in range(X.shape[1])])
    print(X[1:, 1:])
    X[1:, 1:] = R(X[1:, 1:])
    return X
R = R(X)


(3, 1)
(3, 1)
(3, 1)
[[ 6.41170797 -0.29414601]
 [-5.0590221  -1.52951105]]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [299]:
R[abs(R) < 1E-8] = 0
R

TypeError: bad operand type for abs(): 'function'

In [295]:

np.linalg.qr(X.T)[0] * R

TypeError: unsupported operand type(s) for *: 'float' and 'function'

In [297]:
np.linalg.qr(X)[1]

matrix([[-7.34846923, -6.80413817, -3.40206909],
        [ 0.        , -8.16723354, -0.71650355],
        [ 0.        ,  0.        , -1.38294923]])