In [3]:
import numpy as np

In [24]:
def householder_compute(x):
    alpha = x[0, 0] * (1 + np.linalg.norm(x) / abs(x[0, 0]))
    x = x / alpha
    x[0, 0] = 1
    return (x, 2/np.linalg.norm(x)**2)

In [113]:
def householder(x, b, w):
    if b != 0:
        a = float(b * np.matmul(x.T, w))
        x = x - a*w
    return np.squeeze(np.asarray(x))

In [114]:
X = np.matrix([[1,4,2], [2,9, 1], [7,4,3]])

In [115]:
Q = np.matrix([])
for i in range(X.shape[0]):
    x = X[i].T
    w, beta = householder_compute(x)
    K = (beta * np.matmul(w, w.T))
    Q = np.identity(K.shape[0]) - K
    X = Q.T * X
    if Q.shape == (1, 0):
        Q = np.identity(K.shape[0]) - K
    else:
        Q = np.matmul(Q, np.identity(K.shape[0]) - K)
    

In [116]:
Q

matrix([[1.00000000e+00, 1.73472348e-16, 1.11022302e-16],
        [1.73472348e-16, 1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 0.00000000e+00, 1.00000000e+00]])

In [117]:
W = []
B = []

In [201]:
X = np.matrix([[1,4,2], [2,9, 1], [7,4,3]])
def R(X):
    if X.size == 1:
        return X

    w, beta = householder_compute(X[0].T)
    print([householder(x.T, beta, w) for x in X])
    X = (np.matrix([householder(x.T, beta, w) for x in X]))
    X[1:, 1:] = R(X[1:, 1:]).T
    return X.T
R = R(X)


[array([-4.58257569e+00, -8.88178420e-16, -4.44089210e-16]), array([-8.72871561,  1.31271284, -2.84364358]), array([-6.32831882, -5.54994221, -1.7749711 ])]
[array([-3.13201593,  0.        ]), array([ 0.71458616, -5.78288402])]


In [202]:
R[abs(R) < 1E-8] = 0
R

matrix([[-4.58257569, -8.72871561, -6.32831882],
        [ 0.        , -3.13201593,  0.71458616],
        [ 0.        ,  0.        , -5.78288402]])

In [203]:

np.linalg.qr(X.T)[0] * R

matrix([[1., 2., 7.],
        [4., 9., 4.],
        [2., 1., 3.]])

In [204]:
np.linalg.qr(X.T)[1]

matrix([[-4.58257569, -8.72871561, -6.32831882],
        [ 0.        , -3.13201593,  0.71458616],
        [ 0.        ,  0.        , -5.78288402]])