In [6]:
import numpy as np

In [40]:
def function1(X):
    v = np.zeros(X.shape)
    for j in range(X.shape[0]):
        y = np.zeros(X.shape[1])
        for i in range(j):
            r = np.inner(X[j], v[i])
            y += r * v[i]
        v[j] = (X[j] - y)/np.linalg.norm(X[j] - y)
    return v
        

In [41]:
def function2(X):
    v = np.zeros(X.shape)
    for j in range(X.shape[0]):
        w = X[j]
        for i in range(j):
            r = np.inner(w, v[i])
            w = w - r * v[i]
        v[j] = (w)/np.linalg.norm(w)
    return v
        

In [42]:
X = np.array([[1,2,9], [4,3,6], [1,8,3]])

In [43]:
X

array([[1, 2, 9],
       [4, 3, 6],
       [1, 8, 3]])

In [44]:
Y = function1(X)

In [45]:
7/np.linalg.norm([7,8,9])

0.5025707110324167

In [46]:
np.matmul(Y.T, Y)

array([[ 1.00000000e+00,  4.46295437e-18,  1.73797894e-16],
       [ 4.46295437e-18,  1.00000000e+00, -9.54576493e-18],
       [ 1.73797894e-16, -9.54576493e-18,  1.00000000e+00]])

In [47]:
Y2 = function2(X)

In [48]:
Y

array([[ 0.10783277,  0.21566555,  0.97049496],
       [ 0.8903482 ,  0.41337595, -0.1907889 ],
       [-0.44232587,  0.88465174, -0.14744196]])

In [49]:
Y2

array([[ 0.10783277,  0.21566555,  0.97049496],
       [ 0.8903482 ,  0.41337595, -0.1907889 ],
       [-0.44232587,  0.88465174, -0.14744196]])

In [50]:
def GenerateHilbert(n):
    H = np.zeros((n,n))
    for i in range(1, n+1):
        h = [1/(i + j) for j in range(n)]
        H[i-1] = h
    return H
        
            

In [66]:
H = GenerateHilbert(1000)

In [67]:
R1 = function1(function1(H))

In [68]:
R2 = function2(function2(H))

In [69]:
np.matmul(R1.T, R1)

array([[ 1.00000016e+00, -1.05434125e-05,  1.45337584e-04, ...,
        -2.81057963e-04, -2.81130653e-04, -2.81091529e-04],
       [-1.05434125e-05,  1.00070403e+00, -9.70333392e-03, ...,
         1.87751087e-02,  1.87799640e-02,  1.87773509e-02],
       [ 1.45337584e-04, -9.70333392e-03,  1.13370168e+00, ...,
        -2.58954396e-01, -2.59021351e-01, -2.58985318e-01],
       ...,
       [-2.81057963e-04,  1.87751087e-02, -2.58954396e-01, ...,
         5.00612610e-01,  5.00741375e-01,  5.00671274e-01],
       [-2.81130653e-04,  1.87799640e-02, -2.59021351e-01, ...,
         5.00741375e-01,  5.00870173e-01,  5.00800055e-01],
       [-2.81091529e-04,  1.87773509e-02, -2.58985318e-01, ...,
         5.00671274e-01,  5.00800055e-01,  5.00729946e-01]])

In [70]:
np.matmul(R2.T, R2)

array([[ 1.00000000e+00,  7.77093405e-17,  7.72925952e-17, ...,
        -7.80906106e-15, -5.26497217e-15,  1.21035574e-14],
       [ 7.77093405e-17,  1.00000000e+00,  1.40090222e-16, ...,
        -7.19010422e-15, -6.44317786e-15,  1.15348357e-14],
       [ 7.72925952e-17,  1.40090222e-16,  1.00000000e+00, ...,
        -4.60080501e-15, -1.60773280e-15,  5.52040594e-15],
       ...,
       [-7.80906106e-15, -7.19010422e-15, -4.60080501e-15, ...,
         1.00000000e+00,  2.39391840e-16,  1.47451495e-16],
       [-5.26497217e-15, -6.44317786e-15, -1.60773280e-15, ...,
         2.39391840e-16,  1.00000000e+00, -7.97972799e-17],
       [ 1.21035574e-14,  1.15348357e-14,  5.52040594e-15, ...,
         1.47451495e-16, -7.97972799e-17,  1.00000000e+00]])